services:
  postgres:
    user: postgres
    # Custom Dockerfile.postgres within build section is used to add tsearch dictionaries.
    # Comment out the build section to use the default PostgreSQL image.
    build: 
      context: .
      dockerfile: Dockerfile.postgres-tsearch
    # If you want pure PostgreSQL vanilla experience use:
    # image: &pgimage "postgres:latest"
    image: &pgimage postgres-tsearch:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PSQLRC: "/pgwordle/.psqlrc"
    volumes:
      - "./bootstrap.sh:/docker-entrypoint-initdb.d/bootstrap.sh"
      - "./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql"
      - "./:/pgwordle"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5